name: GPG Info
on: workflow_dispatch
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          # These secrets will need to be configured for the repository:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      -
        name: Get default key info
        run: |
          echo "GPG fingerprint: $GPG_FINGERPRINT"
          echo ""
          echo "ASCII armor export:"
          gpg --armor --export $GPG_FINGERPRINT
          echo ""
          echo "ASCII armor export + base64:"
          gpg --armor --export $GPG_FINGERPRINT | openssl enc -a
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
